name: clima
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  geolocator: ^9.0.2
  http: ^1.1.0
  flutter_spinkit: ^5.2.0
  google_maps_flutter: ^2.1.1
  intl: ^0.18.1
  mongo_dart: ^0.10.0
  permission_handler: ^11.2.0
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true

  assets:
  - images/

  fonts:
  - family: Montserrat
    fonts:
    - asset: fonts/Montserrat-Regular.ttf
    - asset: fonts/Montserrat-Medium.ttf
      weight: 500
    - asset: fonts/Montserrat-SemiBold.ttf
      weight: 600